# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/gyusam/UnrealEngine5.5

TARGETS = \
	DroneSim-Android-DebugGame  \
	DroneSim-Android-Development  \
	DroneSim-Android-Shipping  \
	DroneSim-Linux-DebugGame  \
	DroneSim-Linux-Development  \
	DroneSim-Linux-Shipping  \
	DroneSim-LinuxArm64-DebugGame  \
	DroneSim-LinuxArm64-Development  \
	DroneSim-LinuxArm64-Shipping  \
	DroneSim \
	DroneSimEditor-Linux-DebugGame  \
	DroneSimEditor-Linux-Development  \
	DroneSimEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend DroneSimEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug DroneSimEditor-Linux-Debug


DroneSim-Android-DebugGame:
	 $(BUILD) DroneSim Android DebugGame  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-Android-Development:
	 $(BUILD) DroneSim Android Development  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-Android-Shipping:
	 $(BUILD) DroneSim Android Shipping  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-Linux-DebugGame:
	 $(BUILD) DroneSim Linux DebugGame  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-Linux-Development:
	 $(BUILD) DroneSim Linux Development  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-Linux-Shipping:
	 $(BUILD) DroneSim Linux Shipping  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-LinuxArm64-DebugGame:
	 $(BUILD) DroneSim LinuxArm64 DebugGame  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-LinuxArm64-Development:
	 $(BUILD) DroneSim LinuxArm64 Development  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim-LinuxArm64-Shipping:
	 $(BUILD) DroneSim LinuxArm64 Shipping  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSim: DroneSim-Linux-Development

DroneSimEditor-Linux-DebugGame:
	 $(BUILD) DroneSimEditor Linux DebugGame  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSimEditor-Linux-Development:
	 $(BUILD) DroneSimEditor Linux Development  -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" $(ARGS)

DroneSimEditor: DroneSimEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/gyusam/Documents/Unreal Projects/DroneSim/DroneSim.uproject" -Game 

.PHONY: $(TARGETS)
